### ISSUE TITLE
Can't get Baubles Reborn to work with my IDE [1.16]

### ISSUE THREAD

**Issue by Rykita** [lazyMods/Baubles#8]
dependencies {
    minecraft 'net.minecraftforge:forge:1.16.3-34.1.42'
    compile "com.github.lazyMods:Baubles:1.8.2"
}

repositories {
    maven {
        name 'Baubles'
        url 'https://jitpack.io'
    }
}

is my setup, I refreshed the gradle but now I'm greeted with 
"Baubles (baubles) encountered an error during the sided_setup event phase
java.ang.NoSuchMethodError:"

when doing runClient

I'm using 1.16.3, Forge 34.1.42, funnily enough, if I build the mod, it works fine.
Here's the crash report:
[crash-2020-11-17_20.04.12-fml.txt](https://github.com/lazyMods/Baubles/files/5555650/crash-2020-11-17_20.04.12-fml.txt)

I'm not sure where I'm going wrong...

EDIT: Removing baubles altogether from my IDE, including the run/mods directory seems to fix this, but again, no baubles.

**Comment by cech12** [comment]
Maybe it is the same issue like this: https://github.com/lazyMods/Baubles/issues/7

**Comment by Rykita** [comment]
> Maybe it is the same issue like this: #7

Basically from what I see, yeah. I use Forge 34.1.42, latest version of the API (I updated to 34.1.42 from 34.1.0 to see if that'd fix it but it didn't)

**Comment by lazynessmind** [comment]
working on it...

**Comment by lazynessmind** [comment]
-> lazynessmind.github.io 
done :+1:
